name: Testing Build
run-name: Testing Build...
on:
  push:
    branches:
      - main
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set VLIB environment variable
        run: echo "VLIB=${{ github.workspace }}/lib" >> $GITHUB_ENV
      - name: Clean up any previous builds
        run: make clean
      - name: Build the vasm pre-processor
        run: make vpp
      - name: Build the virtual machine itself
        run: make virtmach
      - name: Build the disassembler
        run: make devasm
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Set up Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Set VLIB environment variable
        run: echo "VLIB=${{ github.workspace }}\lib" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Clean up previous builds
        if: always()
        run: .\build_msvc.bat clean
      - name: Build the project (vpp, virtmach, devasm)
        run: .\build_msvc.bat