name: Testing Build
run-name: Testing Build...
on: 
  push:
    branches:
      - main

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Export standard library path for the virtual machine to the terminal
        run: export VLIB="/lib"

      - name: Clean up any previous builds
        run: make clean

      - name: Build the vasm pre-processor
        run: make vpp

      - name: Build the virtual machine itself
        run: make virtmach

      - name: Build the disassembler
        run: make devasm

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Export standard library path for the virtual machine (Windows)
        run: |
          echo "Setting VLIB environment variable"
          setx VLIB "C:\lib"  # Using setx for persisting the env variable for the session
          
      - name: Clean up any previous builds
        run: ./build_msvc.bat clean

      - name: Build
        run: ./build_msvc.bat
